ProjektTNAI/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ProjetTNAI.DataAccessLayer.Repositories.Abstract;
using ProjetTNAI.DataAccessLayer.Repositories.Concrete;
using ProjetTNAI.Entities;
using ProjetTNAI.Entities.Models;

namespace ProjektTNAI.Controllers
{
    public class PlansController : Controller
    {
        private readonly IPlanRepository _planRepository;
        private Random _random = new Random();

        public PlansController(IPlanRepository planRepository, HttpClient httpClient)
        {
            _planRepository = planRepository;
        }

        // GET: Plans
        public async Task<ActionResult> Index()
        {
            var plans = await _planRepository.GetWielePlanowAsync();
            return View(plans);
        }

        // GET: Plans/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var plan = await _planRepository.GetPlanAsync(id.Value);
            if (plan == null)
            {
                return HttpNotFound();
            }

            return View(plan);
        }

        // GET: Plans/Create
        public ActionResult Create()
        {
            var daysOfWeek = new Dictionary<int, string>
            {
                {1, "Poniedziałek"},
                {2, "Wtorek"},
                {3, "Środa"},
                {4, "Czwartek"},
                {5, "Piątek"},
            };
            ViewBag.daysOfWeek = daysOfWeek;
            return View();
        }

        // POST: Plans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Nazwa,Rok,Grupa")] Plan plan)
        {
            if (!ModelState.IsValid)
            {
                return View(plan);
            }

            var token = "";
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            for (var i = 0; i < 5; i++)
            {
                token += chars[_random.Next(chars.Length)];
            }

            plan.KluczEdycji = token;
            


            var result = await _planRepository.ZapiszPlanAsync(plan);
            if (!result)
                return View("Error");

            return View("Token", plan);
        }

        // GET: Plans/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var plan = await _planRepository.GetPlanAsync(id.Value);


            if (plan == null)
            {
                return HttpNotFound();
            }

            plan.KluczEdycji = "";

            return View(plan);
        }

        // POST: Plans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Nazwa,Rok,Grupa,KluczEdycji")]
            Plan plan)
        {
            var chekKey = await _planRepository.CheckKey(plan);

            if (!chekKey)
            {
                @ViewBag.id = plan.Id;
                return View("keyError");
            }

            if (!ModelState.IsValid)
            {
                return View(plan);
            }
            await _planRepository.ZapiszPlanAsync(plan);

            return RedirectToAction("Details", plan);
        }

        // GET: Plans/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var plan = await _planRepository.GetPlanAsync(id.Value);
            if (plan == null)
            {
                return HttpNotFound();
            }

            return View(plan);
        }

        // POST: Plans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var key = Request["key"];

            Plan plan = await _planRepository.GetPlanAsync(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            if (plan.KluczEdycji != key)
            {

                @ViewBag.Id = plan.Id;
                return View("keyError");
            }

            await _planRepository.UsunPlanAsync(plan);

            return RedirectToAction("Index");
        }
    }
}

ProjektTNAI/Controllers/ProwadzacyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetTNAI.Entities;
using ProjetTNAI.Entities.Models;
using ProjetTNAI.DataAccessLayer.Repositories.Abstract;

namespace ProjektTNAI.Controllers
{
    public class ProwadzacyController : Controller
    {
        private readonly IProwadzacyRepository _prowadzacyRepository;

        public ProwadzacyController(IProwadzacyRepository prowadzacyRepository)
        {
            _prowadzacyRepository = prowadzacyRepository;
        }

        // GET: Prowadzacy
        public async Task<ActionResult> Index(int? planId, string editKey)
        {
            List<Prowadzacy> prowadzacy;

            if (planId == null)
                prowadzacy = await _prowadzacyRepository.GetWieluProwadzacychAsync();
            else
                prowadzacy = await _prowadzacyRepository.GetProwadzacyWPlanieAsync(planId.Value);

            if (await _prowadzacyRepository.KeyIsValid(planId, editKey))
                return View(prowadzacy);

            return View(prowadzacy);
        }

        // GET: Prowadzacy/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Prowadzacy prowadzacy = await _prowadzacyRepository.GetProwadzacyAsync(id.Value);
            if (prowadzacy == null)
            {
                return HttpNotFound();
            }

            return View(prowadzacy);
        }

        // GET: Prowadzacy/Create
        public ActionResult Create(string planId, string name)
        {
            ViewBag.planId = planId == null ? (dynamic) planId : "-1";
            ViewBag.name = name == null ? name : "-1";
            return View();
        }

        // POST: Prowadzacy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Imie,Nazwisko,Email")]
            Prowadzacy prowadzacy)
        {
            if (ModelState.IsValid)
            {
                await _prowadzacyRepository.ZapiszProwadzacyAsync(prowadzacy);

                if (Request["planId"] != "")
                {
                    return RedirectToAction("Create", "Classes", new {planId = Request["planId"], name = Request["name"]});
                }
                return RedirectToAction("Index");
            }

       

            return View(prowadzacy);
        }

        // GET: Prowadzacy/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Prowadzacy prowadzacy = await _prowadzacyRepository.GetProwadzacyAsync(id.Value);
            if (prowadzacy == null)
            {
                return HttpNotFound();
            }

            return View(prowadzacy);
        }

        // POST: Prowadzacy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Imie,Nazwisko,Email")]
            Prowadzacy prowadzacy, int? planId, string editKey)
        {
            if (ModelState.IsValid)
            {
                await _prowadzacyRepository.ZapiszProwadzacyAsync(prowadzacy);
                return RedirectToAction("Index");
            }

            return View(prowadzacy);
        }
        
//         }
    }
}

ProjektTNAI/Views/Classes/Create.cshtml
@using ProjektTNAI.Controllers
@using ProjetTNAI.Entities.Models
@model ProjetTNAI.Entities.Models.Zajecia

@{
    ViewBag.Title = "Create";
}

<h2>dodaj zajecia do planu @ViewBag.name</h2>
<div class="form-horizontal">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Nazwa, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LinkDoZajec, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LinkDoZajec, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LinkDoZajec, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DzienTygodnia, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("dayOfWeek", ((SelectList) ViewBag.daysOfWeek))
                @* @Html.EditorFor(model => model.DzienTygodnia, new {htmlAttributes = new {@class = "form-control"}}) *@

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poczatek, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="time" name="startAt" class="form-control">

                @* @Html.ValidationMessageFor(model => model.Rok, "", new {@class = "text-danger"}) *@
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Koniec, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="time" name="finishAt" class="form-control">
                @* @Html.ValidationMessageFor(model => model.Rok, "", new {@class = "text-danger"}) *@
            </div>
        </div>

        <div class="form-group">
            <label for="lectuer" class="control-label col-md-2">wybierz prowadzącego</label>
            <select name="lectures" class="form-select" multiple aria-label="multiple">
                @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>)
                {
                    <option value="@lecture.Id">@lecture.Imie @lecture.Nazwisko</option>
                }
            </select>

            @Html.ActionLink("Dodaj prowadzącego", "Create", "Prowadzacy", new {planId=@ViewBag.planId, name=@ViewBag.name}, null )
        </div>
        <div class="form-group">
            <label for="key" class="control-label col-md-2">klucz edycji </label>
            <input type="text" id="key" placeholder="klucz edycji" name="key" class="btn btn-default"/>
            @* @Html.ActionLink("Back to List", "Index") *@
        </div>
        <input type="hidden" value="@ViewBag.planId" name="planId">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    }
    @* <div class="form-group"> *@
    @*     <div class="col-md-offset-2 col-md-10"> *@
    @*         <input type="button" value="Create" onclick="create()" class="btn btn-default"/> *@
    @*     </div> *@
    @* </div> *@
</div>


@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/createClasses.js")"></script>
}

ProjektTNAI/Views/Classes/Delete.cshtml
@using ProjetTNAI.Entities.Models
@model ProjetTNAI.Entities.Models.Zajecia

@{
    ViewBag.Title = "details";
}
<h2>Zajecia @Html.DisplayFor(model => model.Nazwa)</h2>
<h5 class="dayOfWeek">@Html.DisplayFor(model => model.DzienTygodnia)</h5>
<h6>Godziny zajęć: @Html.DisplayFor(model => model.Poczatek.TimeOfDay) - @Html.DisplayFor(model => model.Koniec.TimeOfDay)</h6>
<h6>Link do zajęć: @Html.DisplayFor(model => model.LinkDoZajec)</h6>

<div>
    <p>Prowadzący zajęcia</p>
    <ul>
        @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>)
        {
            <li> <a class="btn stretched-link" style="color: #0f0f0f" href="@Url.Action("Details", "Prowadzacy", new {id=lecture.Id})"> @lecture.Imie @lecture.Nazwisko  </a></li>
        }

        @* @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>) *@
        @* { *@
        @*     <option value="@lecture.Id">@lecture.Imie @lecture.Nazwisko</option> *@
        @* } *@
    </ul>
</div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="text" placeholder="klucz edycji" name="key" class="btn btn-default" /> 
            @* @Html.ActionLink("Back to List", "Index") *@
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Back to List", "Edit", "Plans",new {id=@Model.PlanId},null)
        </div>
    }
@section Scripts {
    @Scripts.Render("~/Scripts/dayOfWeek.js")
}

ProjektTNAI/Views/Classes/Details.cshtml
@using ProjetTNAI.Entities.Models
@model ProjetTNAI.Entities.Models.Zajecia

@{
    ViewBag.Title = "details";
}
<h2>Zajecia @Html.DisplayFor(model => model.Nazwa)</h2>
<h5 class="dayOfWeek">@Html.DisplayFor(model => model.DzienTygodnia)</h5>
<h6>Godziny zajęć: @Html.DisplayFor(model => model.Poczatek.TimeOfDay) - @Html.DisplayFor(model => model.Koniec.TimeOfDay)</h6>
<h6>Link do zajęć: @Html.DisplayFor(model => model.LinkDoZajec)</h6>

<div>
    <p>Prowadzący zajęcia</p>
    <ul>
        @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>)
        {
            <li> <a class="btn stretched-link" style="color: #0f0f0f" href="@Url.Action("Details", "Prowadzacy", new {id=lecture.Id})"> @lecture.Imie @lecture.Nazwisko  </a></li>
        }

        @* @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>) *@
        @* { *@
        @*     <option value="@lecture.Id">@lecture.Imie @lecture.Nazwisko</option> *@
        @* } *@
    </ul>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/dayOfWeek.js")
}

ProjektTNAI/Views/Classes/Edit.cshtml
@using System.Web.UI.HtmlControls
@using ProjektTNAI.Controllers
@using ProjetTNAI.Entities.Models
@model ProjetTNAI.Entities.Models.Zajecia

@{
    ViewBag.Title = "Edit";
}

<h2>Modyfikuj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edytuj zajecia w Planie @ViewBag.name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.DzienTygodnia)
        @Html.HiddenFor(model => model.Godzina)
        @Html.HiddenFor(model => model.CzasTrwania)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Nazwa, "", new {@class = "text-danger"})
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LinkDoZajec, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LinkDoZajec, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LinkDoZajec, "", new {@class = "text-danger"})
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DzienTygodnia, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("dayOfWeek", ((SelectList) ViewBag.daysOfWeek))
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poczatek, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="time" name="startAt" id="startAt" class="form-control">

                @* @Html.ValidationMessageFor(model => model.Rok, "", new {@class = "text-danger"}) *@
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Koniec, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="time" name="finishAt" id="finishAt" class="form-control">
                @* @Html.ValidationMessageFor(model => model.Rok, "", new {@class = "text-danger"}) *@
            </div>
        </div>

        <div class="form-group">
            <label for="lectuer" class="control-label col-md-2">dodaj prowadzącego</label>
            <select name="lectures" class="form-select" multiple aria-label="multiple">
                @foreach (var lecture in ViewData["lecturers"] as IList<Prowadzacy>)
                {
                    <option value="@lecture.Id">@lecture.Imie @lecture.Nazwisko</option>
                }
            </select>

            @Html.ActionLink("Dodaj prowadzącego", "Create", "Prowadzacy", new {planId=@ViewBag.planId, name=@ViewBag.name}, null )
        </div>

        <div class="form-group">
            <label for="lectuer" class="control-label col-md-2">usun prowadzącego</label>
            <select name="currentLecturers" class="form-select" multiple aria-label="multiple">
                @foreach (var lecture in ViewData["currentLecturers"] as IList<Prowadzacy>)
                {
                    <option value="@lecture.Id">@lecture.Imie @lecture.Nazwisko</option>
                }
            </select>

        </div>
        <div class="form-group">
            <label for="key" class="control-label col-md-2">klucz edycji </label>
            <input type="text" id="key" placeholder="klucz edycji" name="key" class="btn btn-default"/>
            @* @Html.ActionLink("Back to List", "Index") *@
        </div>
        <input type="hidden" value="@ViewBag.planId" name="planId">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>


    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/dayOfWeek.js")
    <script type="text/javascript">
        dayOfWeek = {
                "1":"Poniedziałek",
                "2":"Wtorek",
                "3":"Środa",
                "4":"Czwartek",
                "5":"Piątek",
            }
            
        let el = document.querySelector("select").childNodes;
        console.log(el);
        const day = document.getElementById("DzienTygodnia").value;
        console.log(day)
        for (let i = 0; i<el.length;i++)
        {
            if (el[i].value == day)
                {
                    el[i].setAttribute("selected", "");
                }
        }
        let start = parseInt(document.getElementById("Godzina").value);
        // console.log(start)

        const startAt = new Date(start * 1000);
        let min = startAt.getMinutes();
        if(min < 9)
            min = "0"+min;
        
        let end = parseInt(document.getElementById("CzasTrwania").value) + start;
        const finishAt = new Date(end * 1000);
        let min2 = startAt.getMinutes();
        if(min2 < 9)
            min2 = "0"+min2;
                
        
         console.log(finishAt.getHours()+":"+finishAt.getMinutes());
        document.getElementById("startAt").value = (startAt.getHours()-1)+":"+min;
        document.getElementById("finishAt").value = (finishAt.getHours()-1)+":"+min2;
        
            
    
    </script>

}